name: Publish to Dev

on:
    workflow_dispatch:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout [test-prod]
              if: contains(github.repository, 'test-prod')
              uses: actions/checkout@v4
              with:
                repository: 'matikin9/test-prod'
                ref: 'dev'
                path: 'test-prod'
            - name: Checkout [test-dev]
              if: contains(github.repository, 'test-prod')
              uses: actions/checkout@v4
              with:
                repository: 'matikin9/test-dev'
                ref: 'dev'
                path: 'test-dev'
            - name: 'Copy files'
              if: contains(github.repository, 'test-prod')
              run: |
                  echo "Publishing to Dev"
                  cp -r test-prod/* test-dev/
                  cd test-dev
                  ls -la
                  git status
            - name: 'Commit and push changes'
              if: contains(github.repository, 'test-prod')
              uses: EndBug/add-and-commit@v7
              with:
                  message: Auto publish to Dev
                  committer_name: GitHub Actions
                  committer_email: actions@github.com
            
            